# Generated by Django 5.1.1 on 2024-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jo_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generationticket",
            name="qr_code",
        ),
        migrations.AddField(
            model_name="generationticket",
            name="qr_code_url",
            field=models.URLField(blank=True),
        ),
    ]
