# Generated by Django 5.1.1 on 2024-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0002_remove_generationticket_qr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationticket',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='generationticket',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='generationticket',
            name='date_generation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
