# Generated by Django 5.1.1 on 2024-09-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jo_app", "0003_remove_generationticket_qr_code_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationticket",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_codes/"),
        ),
    ]
