# Generated by Django 5.1.1 on 2024-09-23 21:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0004_alter_generationticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationticket',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
