# Generated by Django 5.1.1 on 2024-09-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jo_app", "0006_alter_generationticket_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationticket",
            name="qr_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
