# Generated by Django 5.1.1 on 2024-09-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0007_alter_generationticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationticket',
            name='qr_code',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
