# Generated by Django 5.1.1 on 2024-09-09 14:29

import datetime
import django.db.models.deletion
import django.utils.timezone
import jo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('famille', 'Famille')], max_length=10)),
                ('prix_solo', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('prix_duo', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
                ('prix_famille', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('nom_evenement', models.CharField(max_length=100)),
                ('date_evenement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('NB', 'Non-binaire')], default='H', max_length=5)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mot_de_passe', models.CharField(max_length=50, validators=[jo_app.models.validate_password])),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(default='00000', max_length=10)),
                ('ville', models.CharField(default='Inconnue', max_length=50)),
                ('date_de_naissance', models.DateField(default=datetime.date.today)),
                ('date_d_inscription', models.DateField(auto_now_add=True)),
                ('est_administrateur', models.BooleanField(default=False)),
                ('cle_securisee_1', models.CharField(blank=True, editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode_paiement', models.CharField(max_length=50)),
                ('statut_paiement', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='jo_app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
                ('cle_securisee_2', models.CharField(blank=True, editable=False, max_length=50)),
                ('quantite_vendue', models.IntegerField(default=0)),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tickets', to='jo_app.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='jo_app.utilisateur'),
        ),
    ]
