# Generated by Django 5.1.1 on 2024-09-13 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_evenement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('NB', 'Non-binaire')], default='H', max_length=5)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField(default='2000-01-01')),
                ('date_d_inscription', models.DateField(auto_now_add=True)),
                ('cle_securisee_1', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('famille', 'Famille')], max_length=10)),
                ('prix_solo', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('prix_duo', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
                ('prix_famille', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('sport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jo_app.sport')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode_paiement', models.CharField(max_length=50)),
                ('statut_paiement', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='jo_app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('cle_securisee_2', models.CharField(blank=True, editable=False, max_length=64)),
                ('quantite_vendue', models.IntegerField(default=0)),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tickets', to='jo_app.ticket')),
            ],
        ),
    ]
