# Generated by Django 5.1.1 on 2024-09-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_de_naissance',
        ),
    ]
