# Generated by Django 5.1.1 on 2024-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('NB', 'Non-binaire')], default='H', max_length=5),
        ),
    ]
