# Generated by Django 5.1.1 on 2024-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationticket',
            name='cle_securisee_2',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='cle_securisee_1',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
