# Generated by Django 5.1.1 on 2024-09-09 13:36

import jo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0002_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(max_length=50, validators=[jo_app.models.validate_password]),
        ),
    ]
