# Generated by Django 5.1.1 on 2024-09-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0002_ticket_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/sports/'),
        ),
    ]
