# Generated by Django 5.1.1 on 2024-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0002_remove_utilisateur_date_de_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
