# Generated by Django 5.1.1 on 2024-09-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0003_utilisateur_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationticket',
            name='cle_securisee_2',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='generationticket',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='cle_securisee_1',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
