# Generated by Django 5.1.1 on 2024-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0003_sport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
