# Generated by Django 5.1.1 on 2024-09-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0004_sport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='est_achete',
            field=models.BooleanField(default=False),
        ),
    ]
