# Generated by Django 5.1.1 on 2024-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0004_alter_generationticket_cle_securisee_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='code_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_de_naissance',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(max_length=50),
        ),
    ]
