# Generated by Django 5.1.1 on 2024-09-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0005_alter_utilisateur_code_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_evenement', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_evenement',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='nom_evenement',
        ),
        migrations.AddField(
            model_name='ticket',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jo_app.sport'),
        ),
    ]
