# Generated by Django 5.1.1 on 2024-09-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0006_sport_remove_ticket_date_evenement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jo_app.sport'),
        ),
    ]
